apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment-app
spec:
  selector:
    matchLabels:
      app: api-gateway-deployment-app
  template:
    metadata:
      labels:
        app: api-gateway-deployment-app
    spec:
      containers:
      - name: api-gateway-deployment-app
        image: Lokeshkhadse/apiGateway
        ports:
        - containerPort: 1002
        env:
           - name: EUREAK_SERVER_ADDRESS #THIS IS NAME WHICH WE ADD IN APPLICATION.PROPERTIES CONFIG-SERVICE
             valueFrom:
               configMapKeyRef:
                 key: eureka_service_address   # this key is present in config-map.yaml
                 name: eureka-config-map        # config-map yaml file this metadat name
        
           - name: CONFIG_SERVER_URL 
             valueFrom:
               configMapKeyRef:
                 key: config_url  
                 name: config-service-config-map        


---
#expose port using service
# type : LoadBalancer because traffic will comne to thisn api-gateway and it will decide where to route this

apiVersion: v1
kind: Service
metadata:
  name: api-gateway-servcie-svc
spec:
  type: LoadBalancer
  selector:
    app: api-gateway-deployment-app
  ports:
  - port: 80
    targetPort: 1002

---
 
