
# eureka is statefulset so that's y it is statefulset deployement file
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eureka
spec:
  selector:
    matchLabels:
      app: eureka
  serviceName: "eureka"
  replicas: 2
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
      - name: myapp
        image:  pull image of service -registry which you create for that service and upload on dockerhub
        ports:
        - containerPort: 8761
       


---
#service file to expose prt and things
# it is also for the internally connect to application

apiVersion: v1
kind: Service
metadata:
  name: eureka
spec:
  clusterIP: None  # means it is headless service when you want to directly access the individual Pods behind a service
  selector:
    app: eureka
  ports:
  - port: 8761
    name: eureka


---
#outside cluster also access this service registry with help of NodePort and loadBalancing
# it is also for the externally connect to application

apiVersion: v1
kind: Service
metadata:
  name: eureka-lb
spec:
  type: NodePort
  selector:
    app: eureka
  ports:
  - port: 80
    targetPort: 8761

